recipe: default.v1
language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
- name: FallbackClassifier
  threshold: 0.3  # Set a relatively low threshold to avoid triggering on order IDs
- name: NLUCommandAdapter
# - name: SingleStepLLMCommandGenerator
#   llm:
#     model_group: rasa_command_generation_model
#   flow_retrieval:
#     active: false

policies:
- name: FlowPolicy
- name: RulePolicy
- name: MemoizationPolicy
  max_history: 5
- name: TEDPolicy
  max_history: 5
  epochs: 100

#  - name: EnterpriseSearchPolicy
assistant_id: 20250205-050742-corporate-leopard
